"""Qt resource packages shared by the editor and Hub."""
from __future__ import annotations

import importlib
import os
import sys
from pathlib import Path, PurePosixPath

from PySide6.QtCore import QFile, QIODevice, QUrl

try:
    __compiled__
    _COMPILED = True
except NameError:
    _COMPILED = False


class ResourcePackage:
    def __init__(self, name: str, root: Path, *, compiled: bool | None = None):
        self.Root = root.resolve()
        self.Name = name
        self.Compiled = (_COMPILED or getattr(sys, "frozen", False)
                         or os.environ.get("BAZZALT_COMPILED_RESOURCES") == "1") if compiled is None else compiled
        if self.Compiled:
            try:
                # Generated by scripts/compile_resources.py; included as code by Nuitka.
                importlib.import_module(f"bazzalt._{name}_resources_rc")
            except ImportError as error:
                raise RuntimeError(f"Compiled {name} resources are missing. Rebuild or repair this application.") from error

    def Path(self, relative: str | Path, *, required: bool = True) -> str:
        raw = str(relative).replace("\\", "/")
        parts = PurePosixPath(raw)
        if not raw or parts.is_absolute() or ".." in parts.parts or ":" in raw:
            raise ValueError("Resource path must be relative and stay inside its package")
        if self.Compiled:
            result = f":/bazzalt/{self.Name}/{parts.as_posix()}"
            exists = QFile.exists(result)
        else:
            path = (self.Root / parts.as_posix()).resolve()
            if not path.is_relative_to(self.Root):
                raise ValueError("Resource path must stay inside its package")
            result = str(path)
            exists = path.is_file()
        if required and not exists:
            raise FileNotFoundError(f"{self.Name} resource does not exist: {relative}")
        return result

    def ReadBytes(self, relative: str | Path) -> bytes:
        path = self.Path(relative)
        if not self.Compiled:
            return Path(path).read_bytes()
        file = QFile(path)
        if not file.open(QIODevice.OpenModeFlag.ReadOnly):
            raise OSError(f"Cannot read compiled resource: {relative}")
        try:
            return bytes(file.readAll())
        finally:
            file.close()

    def ReadText(self, relative: str | Path, encoding: str = "utf-8") -> str:
        return self.ReadBytes(relative).decode(encoding)

    def Url(self, relative: str | Path) -> QUrl:
        path = self.Path(relative)
        return QUrl("qrc" + path) if self.Compiled else QUrl.fromLocalFile(path)


def Package(name: str, *, compiled: bool | None = None) -> ResourcePackage:
    root = Path(__file__).resolve().parent.parent
    sources = {"editor": root / "Editor/assets", "hub": root / "Launcher", "branding": root / "Launcher"}
    return ResourcePackage(name, sources[name], compiled=compiled)
