set(BAZZALT_LUA_DIR "${CMAKE_SOURCE_DIR}/deps/lua" CACHE PATH "Pinned Lua source")
set(BAZZALT_SOL2_DIR "${CMAKE_SOURCE_DIR}/deps/sol2" CACHE PATH "Pinned Sol2 headers")
if(NOT EXISTS "${BAZZALT_LUA_DIR}/src/lua.h" OR NOT EXISTS "${BAZZALT_SOL2_DIR}/include/sol/sol.hpp")
    message(FATAL_ERROR "Lua/Sol2 missing. Run scripts/get_lua and scripts/get_sol2 (.ps1 or .sh).")
endif()
file(GLOB _lua_sources "${BAZZALT_LUA_DIR}/src/*.c")
list(REMOVE_ITEM _lua_sources "${BAZZALT_LUA_DIR}/src/lua.c" "${BAZZALT_LUA_DIR}/src/luac.c" "${BAZZALT_LUA_DIR}/src/onelua.c")
add_library(BazzaltLua SHARED ${_lua_sources})
target_include_directories(BazzaltLua PUBLIC "${BAZZALT_LUA_DIR}/src")
set_target_properties(BazzaltLua PROPERTIES OUTPUT_NAME bazzalt_lua VERSION 5.4.9 SOVERSION 5.4
    RUNTIME_OUTPUT_DIRECTORY "${CMAKE_BINARY_DIR}/Editor" LIBRARY_OUTPUT_DIRECTORY "${CMAKE_BINARY_DIR}/Editor")
if(WIN32)
    target_compile_definitions(BazzaltLua PRIVATE LUA_BUILD_AS_DLL)
elseif(APPLE)
    target_compile_definitions(BazzaltLua PRIVATE LUA_USE_MACOSX)
else()
    target_compile_definitions(BazzaltLua PRIVATE LUA_USE_LINUX)
    target_link_libraries(BazzaltLua PRIVATE m ${CMAKE_DL_LIBS})
endif()
