name: Windows 64-bit

on:
  push:
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: windows-64-bit-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-and-test:
    uses: ./.github/workflows/windows-product.yml
    with:
      product: editor
      architecture: x64
